name = "what-if-ai"
main = "src/main.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2023-12-18"

[vars]
CLOUDFLARE_API_KEY="I0yDqCpEd6XX_NsTHR6TEwRlPk6xShOc3Tb9F3eX"
CLOUDFLARE_ACCOUNT_ID="6d55e287cc5c5266c3120f39dd54ecc8"
